version: "3.8"

services:
  dev_page:
    image: maheshmaha/dev-page:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  test_page:
    image: maheshmaha/test-page:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  priprod_page:
    image: maheshmaha/priprod-page:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  prod_page:
    image: maheshmaha/prod-page:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
